"""Add product options

Revision ID: 171ada7615a6
Revises: 970ebb02648d
Create Date: 2026-05-06 14:41:02.581152

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "171ada7615a6"
down_revision: str | None = "970ebb02648d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
