"""Make option_item_id nullable

Revision ID: 1d9567c9d5e4
Revises: 171ada7615a6
Create Date: 2026-05-06 14:44:42.899492

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d9567c9d5e4"
down_revision: str | None = "171ada7615a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_item_options", "option_item_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        "order_item_options_option_item_id_fkey", "order_item_options", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "order_item_options",
        "product_option_items",
        ["option_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_item_options", type_="foreignkey")
    op.create_foreign_key(
        "order_item_options_option_item_id_fkey",
        "order_item_options",
        "product_option_items",
        ["option_item_id"],
        ["id"],
    )
    op.alter_column(
        "order_item_options", "option_item_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
