"""add_image_path_to_product

Revision ID: 2a9699ea4f06
Revises: 37fe72372c02
Create Date: 2026-05-07 15:32:54.269706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9699ea4f06'
down_revision: Union[str, None] = '37fe72372c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_path')
    # ### end Alembic commands ###
