"""add_promotion_fields_to_options

Revision ID: 37fe72372c02
Revises: ec70d03187fa
Create Date: 2026-05-06 15:58:57.981005

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37fe72372c02"
down_revision: str | None = "ec70d03187fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_option_items",
        sa.Column("is_promotional", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "product_option_items",
        sa.Column("promotional_price", sa.Numeric(precision=10, scale=2), nullable=True),
    )
    op.add_column(
        "product_option_items",
        sa.Column(
            "promotion_active_days",
            sa.String(length=20),
            server_default="0,1,2,3,4,5,6",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_option_items", "promotion_active_days")
    op.drop_column("product_option_items", "promotional_price")
    op.drop_column("product_option_items", "is_promotional")
    # ### end Alembic commands ###
