"""add_promotional_fields_to_product

Revision ID: 680eacaeee84
Revises: d0049c4a106b
Create Date: 2026-04-29 15:21:56.938182

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "680eacaeee84"
down_revision: str | None = "d0049c4a106b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("is_promotional", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "products", sa.Column("promotional_price", sa.Numeric(precision=10, scale=2), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "promotional_price")
    op.drop_column("products", "is_promotional")
    # ### end Alembic commands ###
