"""add_order_editing_fields

Revision ID: 970ebb02648d
Revises: 680eacaeee84
Create Date: 2026-04-29 16:09:34.302287

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "970ebb02648d"
down_revision: str | None = "680eacaeee84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("is_edited", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("orders", sa.Column("edit_note", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "edit_note")
    op.drop_column("orders", "is_edited")
    # ### end Alembic commands ###
