"""add_option_quantities_and_constraints

Revision ID: b5f85efe8bff
Revises: 1d9567c9d5e4
Create Date: 2026-05-06 15:26:59.029799

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5f85efe8bff"
down_revision: str | None = "1d9567c9d5e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_item_options",
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column("product_option_items", sa.Column("target_group_id", sa.Integer(), nullable=True))
    op.add_column(
        "product_option_items", sa.Column("target_max_value", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_option_items", "target_max_value")
    op.drop_column("product_option_items", "target_group_id")
    op.drop_column("order_item_options", "quantity")
    # ### end Alembic commands ###
