"""Add promotions table

Revision ID: c57279927dcc
Revises: a1b2c3d4e5f6
Create Date: 2026-05-12 15:13:07.576585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c57279927dcc'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('option_item_id', sa.Integer(), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active_days', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_item_id'], ['product_option_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)

    op.drop_column('product_option_items', 'promotional_price')
    op.drop_column('product_option_items', 'is_promotional')
    op.drop_column('product_option_items', 'promotion_active_days')
    op.drop_column('products', 'promotional_price')
    op.drop_column('products', 'is_promotional')
    op.drop_column('products', 'promotion_active_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('promotion_active_days', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_promotional', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('promotional_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('product_option_items', sa.Column('promotion_active_days', sa.VARCHAR(length=20), server_default=sa.text("'0,1,2,3,4,5,6'::character varying"), autoincrement=False, nullable=True))
    op.add_column('product_option_items', sa.Column('is_promotional', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('product_option_items', sa.Column('promotional_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.drop_table('promotions')
    # ### end Alembic commands ###
