"""add_promotion_active_days

Revision ID: ec70d03187fa
Revises: b5f85efe8bff
Create Date: 2026-05-06 15:48:02.785846

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec70d03187fa"
down_revision: str | None = "b5f85efe8bff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("promotion_active_days", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "promotion_active_days")
    # ### end Alembic commands ###
